### PR TITLE
Use js-side https check to prevent an infinite redirection loop when lighttpd is behind a reverse proxy

### PR DESCRIPTION
**Pull request by Grief**
Hope that commit message is self-explanatory. It only changes server-side https check with js-side one. Server-side check is unreliable in cases when there are other web servers in front of lighttpd.

### CODE REVIEW

**Comment by VojtechMyslivec** [comment]
@aleksan4eg would you look at this, please?

**Comment by shenek** [comment]
Makes perfect sense. Dealing with https redirect in the browser seems more error prune.

**Review by shenek — APPROVED** [review]

**Comment by Cynerd** [comment]
Looking in to this... this removes skip of redirection when wizard is not finished. Is this intentional? There is nothing about it in commit message so it looks to me like overlooked impact.

**Comment by Grief** [comment]
@Cynerd Well, I don't think that the behavior when the wizard is **not** finished was changed at all. Look:

```
if [ "$WIZARD_FINISHED" = "1" ]; then

// CHANGES ARE DONE HERE

else
  cat << HTML
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Cache-Control" content="no-cache" />
		<meta http-equiv="refresh" content="$DELAY; URL=$SCRIPTNAME/config/" />
	</head>
	<body>
		<script>
		window.onload = function () {
			location.replace("$SCRIPTNAME/config/");
		};
		</script>
		<p>Continue to <a href="$SCRIPTNAME/config/">first run wizard</a>...</p>
	</body>
</html>
HTML
fi
```
So, when WIZARD_FINISHED is zero, this html is produced. it contains neither HTTPS_REDIRECT nor REDIRECT_SCRIPT, so it can not be any different from what was produced before my change.

The only thing which is doubtable is the removal of REDIRECT_SCRIPT variable which is set to empty string at the beginning of script when wizard **is** finished. I did a quick search and for me it looks like just as an unused variable: https://github.com/search?q=org%3ACZ-NIC+REDIRECT_SCRIPT&type=code

**Comment by Cynerd** [comment]
Eah you are right. I was confused by line 25 (that I see is invalid name of variable and in reality that variable is not even used).

**Review by Cynerd — APPROVED** [review]

**Comment by Cynerd** [comment]
@aleksan4eg @MarekSasek ping..

**Review by MarekSasek — COMMENTED** [review]
Maybe I got it wrong, but new solution works when it is not **https** and old one worked when it is **https**. Is it right and why?

**Comment by Grief** [comment]
> Maybe I got it wrong, but new solution works when it is not **https** and old one worked when it is **https**. Is it right and why?

Both versions do a redirect when the current schema is NOT `https`. Previously on line https://github.com/CZ-NIC/turris-os-packages/pull/62/files#diff-879df6fa1b3de5d707f653e55f23c5a6f7f984fccc44e3eb1af993cb1e9d6545L26, variable, containing the redirection was erased from the page. Now the conditional is on the line https://github.com/CZ-NIC/turris-os-packages/pull/62/files#diff-879df6fa1b3de5d707f653e55f23c5a6f7f984fccc44e3eb1af993cb1e9d6545R114

**Comment by MarekSasek** [comment]
Thank you for your explanation. Now I can see it.

**Review by MarekSasek — APPROVED** [review]

**Comment by BKPepe** [comment]
I was trying to merge this, but I found that we are not using this in our development branch, where we are preparing Turris OS 5.2 for you.

It was removed in this commit https://gitlab.nic.cz/turris/webapps/-/commit/13cb463d60e68f33e07e43509fcde5ce341408db and now there is just this CGI script:
https://gitlab.nic.cz/turris/webapps/-/blob/master/turris-webapps-json-cgi

This could be merged into fixup release if there are good reasons, however, I can not introduce such change in last minute fixup release.

**Comment by BKPepe** [comment]
Turris OS 5.2 was released last week and because of that, I'm closing this.

**Pull request closed without merging**
