### PR TITLE
utils/collectd: Update to the latest upstream state

### PR DESCRIPTION
**Pull request by SuperQ**
* Update to the latest upstream state
* Enable [Write Prometheus](https://collectd.org/wiki/index.php/Plugin:Write_Prometheus) plugin.

### CODE REVIEW

**Comment by miska** [comment]
Hi,

thank you for your pull request, but unfortunately it doesn't unpack so it doesn't build as well:

Applying ./patches/003-remove-werror.patch using plaintext: 
patching file src/Makefile.am
Hunk #1 FAILED at 7.
1 out of 1 hunk FAILED -- saving rejects to file src/Makefile.am.rej
patching file src/Makefile.in
Hunk #1 FAILED at 1833.
1 out of 1 hunk FAILED -- saving rejects to file src/Makefile.in.rej
patching file src/libcollectdclient/Makefile.am
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file src/libcollectdclient/Makefile.am.rej
patching file src/libcollectdclient/Makefile.in
Hunk #1 FAILED at 327.
1 out of 1 hunk FAILED -- saving rejects to file src/libcollectdclient/Makefile.in.rej
can't find file to patch at input line 47
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/src/owniptc/Makefile.am
|+++ b/src/owniptc/Makefile.am
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 58
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/src/owniptc/Makefile.in
|+++ b/src/owniptc/Makefile.in
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Patch failed!  Please fix ./patches/003-remove-werror.patch!

**Comment by SuperQ** [comment]
Strange, I'm not sure where this `003-remove-werror.patch` error is coming from, but it seems unrelated to my patch.  I will rebase this change.

If there are build instructions that I can follow to try to reproduce this error, that would be useful.

**Comment by SuperQ** [comment]
Ok, I figured out the problem, I had forgotten to remove the obsolete patches from the update.  It should apply/build now.

**Comment by ja-pa** [comment]
It will probably require some additional changes. Right now compilation it ends with error 
 

> 

  CC       libcollectdclient_la-client.lo
client.c: In function 'lcc_response_free':
client.c:248:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < res->lines_num; i++)
   ^
client.c:248:3: note: use option -std=c99 or -std=gnu99 to compile your code
client.c: In function 'lcc_open_netsocket':
client.c:469:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (struct addrinfo *ai_ptr = ai_res; ai_ptr != NULL;
   ^
client.c: In function 'lcc_putval':
client.c:734:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < vl->values_len; i++) {
   ^
client.c: In function 'lcc_listval':
client.c:847:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < res.lines_num; i++) {
   ^

**Comment by markusressel** [comment]
Any update on this? I would love to be able to use a collectd version that isn't years behind.

**Comment by SuperQ** [comment]
I've rebased and updated the collectd package to the latest upstream package.  I still haven't been able to find any documentation on how to setup a Turris build environment, so I have no way to test this.

If someone could point me to documentation, I could build this myself and try and make sure it works before submitting it.

**Comment by Cynerd** [comment]
> If someone could point me to documentation, I could build this myself and try and make sure it works before submitting it.

https://doc.turris.cz/doc/en/howto/turris_os_build

**Comment by Cynerd** [comment]
Upstream version of Collectd is used in TOS 4.0+. I am closing this as no longer relevant.

**Pull request closed without merging**
