### PR TITLE
Update git with upstream version

### PR DESCRIPTION
**Pull request by sakulisko**
*Update to upstream version of git client
+Add git-http package with git http support

### CODE REVIEW

**Comment by oskar456** [comment]
Please, don't divert from OpenWRT upstream unless necessary. There is a [pull request](https://github.com/openwrt/packages/pull/1588) in the OpenWRT packages repository for updating to the most recent release plus fixing the symlink bug.

**Comment by sairon** [comment]
Yep, I think that this PR should be postponed until PR by @oskar456 is merged into upstream. We will backport upstream package afterwards. If you propose any changes in that package, please submit them as PRs to openwrt/packages.

By the way, PRs should be submitted against the branch "test". I know it is a bit confusing, since there's no information about it, but it's now at least the default branch, to make it clearer.

**Comment by sakulisko** [comment]
This PR is for updating GIT to the same version as in OpenWRT upstream not diverting from it.

**Comment by oskar456** [comment]
The PR in the upstream is merged, feel free to import it into Turris OS repository.

**Comment by sairon** [comment]
Thanks for the heads up, I've backported latest revision of the Git package to our repository. It should be available in the next release (i.e. Turris OS 2.5).

**Pull request closed without merging**
