### PR TITLE
lighttpd conf cleanup

### PR DESCRIPTION
**Pull request by gstrauss**
lighttpd conf cleanup

x-ref:
https://gitlab.nic.cz/turris/turris-os-packages/-/issues/474
https://gitlab.nic.cz/turris/turris-os-packages/-/issues/559
https://gitlab.nic.cz/turris/turris-os-packages/-/issues/665
https://gitlab.nic.cz/turris/turris-os-packages/-/issues/705

Please review the commits individually.  There may be one or two which you choose to defer or omit.

### CODE REVIEW

**Comment by BKPepe** [comment]
@gstrauss Thank you for your contribution! We will go through all these changes and I'm currently testing your proposed change to start re/Foris on demand.

I noticed just one thing, which is not your fault, but ours. In file reforis-lighttpd-dynamic.sh on the last row, there is specified exact version of Python3. There should be X.X as it is done in Foris's config.

We value contributors and we decided to prepare for you some gift! We will reach you soon.

**Comment by gstrauss** [comment]
Thanks @BKPepe 

When you test lighttpd 1.4.56, please also pick up at least one patch from https://github.com/openwrt/packages/tree/master/net/lighttpd/patches which fixes a new change in lighttpd 1.4.56 and tweaks the compile-time detection logic for _ATFILE_SOURCE on openwrt (020-webdav-atfile.patch).

**Comment by VojtechMyslivec** [comment]
@gstrauss thanks, this is perfect :+1: 

@BKPepe we should consolidate linked issues then and move them to either 5.2.0 or 5.3.0 release. As 5.3.0 release is dedicated to reForis, this would suit up a bit more.

**Comment by BKPepe** [comment]
This is going definitely to be included in Turris OS 5.2.0, I am not waiting for 5.3.0, because right now what is left to us are two things - review it and test it. However, I just tested this PR partially and more testing will be done on Monday or later.

**Comment by gstrauss** [comment]
I rebased my branch onto tip of master and added a commit to update to lighttpd 1.4.57

lighttpd 1.4.57 is a bugfix-only release which fixes some issues discovered in lighttpd 1.4.56

@BKPepe please let me know if you'd like me to try to submit this (or parts of this) to gitlab.nic.cz/turris/turris-os-packages

**Comment by BKPepe** [comment]
- Commits:

- [x]  [Move server.max-read-idle to Foris and reForis](https://github.com/CZ-NIC/turris-os-packages/pull/63/commits/2cfb7c7dfd32ce09f4311e18bbed3cfe46f82cf0)
applied in https://gitlab.nic.cz/turris/turris-os-packages/-/commit/c3c6bcd4ab035b7c79cceb19cf3d7a81339f8f61
- [x]  [Start Foris CGI backends on demand](https://github.com/CZ-NIC/turris-os-packages/pull/63/commits/e621186e89bdab6eba2afa86940096f3e2059b29)
applied in https://gitlab.nic.cz/turris/turris-os-packages/-/commit/7182c53004ed8aeefef2e00c2cd931ca48b5146e
- [x] [Remove lighttpd-mod-ticket](https://github.com/CZ-NIC/turris-os-packages/pull/63/commits/6d1a4393f22f9a5f775afc4da219f47bfdb40226)
applied in https://gitlab.nic.cz/turris/turris-os-packages/-/commit/4d3ed7451e8d358823ff8ffa8972e0a20bac9c3c

Others are still investigated.

- Update of Lighttpd will be solved within this PR: https://gitlab.nic.cz/turris/turris-os-packages/-/merge_requests/422 as I prepared switch to Meson and it seems to be working (run and compile tested).  Your commits are there included. Otherwise, we were missing some important modules in lighttpd and they were not compiled - described in the commit message.

Somehow I end up with applied all changes while testing it and it seems that I hit some issue with Foris (reForis works):
```
Dec 26 21:34:22 omnia lighttpd[2122]: foris: error: unrecognized arguments: 
Dec 26 21:34:24 omnia lighttpd[2122]: usage: foris [-h] [--version] [-H HOST] [-p PORT]
Dec 26 21:34:24 omnia lighttpd[2122]:              [--session-timeout SESSION_TIMEOUT] [-s {wsgiref,flup,cgi}] [-d]
Dec 26 21:34:24 omnia lighttpd[2122]:              [--noauth] [-R] [-S] [-a {config}] [-b {ubus,unix-socket,mqtt}]
Dec 26 21:34:24 omnia lighttpd[2122]:              [--mqtt-port MQTT_PORT] [--mqtt-host MQTT_HOST]
Dec 26 21:34:24 omnia lighttpd[2122]:              [--mqtt-passwd-file MQTT_PASSWD_FILE]
Dec 26 21:34:24 omnia lighttpd[2122]:              [--mqtt-controller-id MQTT_CONTROLLER_ID]
Dec 26 21:34:24 omnia lighttpd[2122]:              [--bus-socket BUS_SOCKET] [--ws-port WS_PORT]
Dec 26 21:34:24 omnia lighttpd[2122]:              [--wss-port WSS_PORT] [--ws-path WS_PATH] [--wss-path WSS_PATH]
Dec 26 21:34:24 omnia lighttpd[2122]:              [-A ASSETS] [-l LOG_FILE]
```

I will look at it closer.

**Comment by gstrauss** [comment]
@BKPepe I have released lighttpd 1.4.58 with some additional bugfixes.  There are no known remaining issues with the (major) release of lighttpd 1.4.56 a month ago.  Please pick up the same change I submitted upstream to openwrt: https://github.com/openwrt/packages/pull/14355

**Comment by gstrauss** [comment]
FYI: lighttpd 1.4.59 was released 2 Feb and is already upstream in OpenWRT.

**Comment by BKPepe** [comment]
That's going to be part of Turris OS 5.2.0. I updated it almost a week ago. Commit: https://github.com/CZ-NIC/turris-os-packages/commit/2533b50e38b31a761d112cc5f9f8e1c8185aa898

**Comment by gstrauss** [comment]
@BKPepe how are things going?  Some patches have been incorporated into Turris OS 5.2.0, but others were backed out and delayed to future Turris OS releases.  Do you have any details about why you had to revert some of the changes?  If you describe the issues, I'll try to reproduce the issues and address them.  Thanks.

**Comment by gstrauss** [comment]
Some optimizations remain in this patchset for web/foris/foris/files/lighttpd-dynamic-conf, but I have not looked closely to see what else might be outstanding.

@BKPepe, if you have time to collaborate, I'm happy to reassess more in-depth.

**Comment by BKPepe** [comment]
Foris will be removed in upcoming version Turris OS 6.0, which is based on OpenWrt 21.02 and hopefully, I will do some changes related using upstream lighttpd version as you said in one of those issues in our GitLab instance.

**Comment by gstrauss** [comment]
Looks like web/foris/foris/files/lighttpd-dynamic-conf has been removed along with the rest of Foris, in favor of reForis for Turris 6.0

(This PR was made against CZ-NIC:master branch, which it appears has since been renamed to 'develop')

**Comment by gstrauss** [comment]
It appears that other PRs on Turris gitlab incorporated the rest of the patches in this PR, besides the patches to Foris, which has been removed.  Therefore, I think this can be closed.

**Pull request closed without merging**
